#!/bin/bash

usage()
{
echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
}

if [ "$#" -lt 4 ]; then
usage
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

if [ ! -f "$FILE_PATH" ]; then
echo "Error: File '$FILE_PATH' does not exist."
exit 1
fi

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/home

if [ "$?" -eq 0 ]; then
echo "File Transferred Successfully to $USERNAME@$SERVER_IP:~/"
else
echo "Error: File transfer failed."
fi
