#!/bin/bash

apt-get update

apt-get install -y nginx

cat <<EOF > /etc/nginx/sites-available/default
server {
listen 80 default_server;
listen[::]:80 default_server;

root /var/www/html
index index.html index.htm index.nginx-debian.html

server_name _;

location / {
try_files \$uri \$uri/ = 404;
}

location = / {
echo "Hello World!";
}
}
EOF

/etc/init.d/nginx restart
