#!/usr/bin/env bash

# a script that displays the content of the file /etc/passwd
# script should only display username, user id, home directory path for the user
# must use while loop (for and until are forbidden)

input="/etc/passwd"

while IFS= read -r line
do
	echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
