#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# only display username, user id, home directory path for the user
# must use while loop
input="/etc/passwd"
while IFS= read -r line
do
echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
