#!/usr/bin/env bash
# we have parse apache log file, sort data we get a better idea
# of what's going on: script groups visitors by IP and HTTP status code
# displays: format: OCCURENCE_NUMBER IP HTTP_CODE, in list format
# ordered from the gr to the lw, must use awk
awk '{
	# extracting IP and HTTP status code
	ip = $1
	code = $9

	# increment the count 
	counts[ip" "code]++
}
END {
	#print results
	for (key in counts) {
		print counts[key], key
	}
}' apache-access.log | sort -nr
