#!/usr/bin/env bash

# now that we have parse the apache log file, let's sort the data so that we get a better idea
# of what's going on
# script that groups visitors by IP and HTTP status code and displays this data
# format must be: OCCURENCE_NUMBER IP HTTP_CODE, in list format
# ordered from the greatest to the lowest number of occurrences
# must use awk, not to use while, for, until and cut

awk '{
	# extracting IP and HTTP status code
	ip = $1
	code = $9

	# increment the count 
	counts[ip" "code]++
}
END {
	#print results
	for (key in counts) {
		print counts[key], key
	}
}' apache-access.log | sort -nr
