#!/usr/bin/env bash
# displays numbers from 1 to 20, 4, bad luck from China 
# 9, bad luck from Japan, 17, bad luck from Italy, while, case
count="0"
while [ $count -le 20 ]
do
case $count in
	4) echo $count
		echo "bad luck from China"
	;;
	9) echo $count
		echo "bad luck from Japan"
	;;
	17) echo $count
		echo "bad luck from Italy"
	;;
	*) echo $count
esac
(( count++ ))
done
