#!/usr/bin/env bash

# script that displays numbers from 1 to 20
# displays 4 then bad luck from China for the 4th loop
# displays 9 then bad luck from Japan for the 9th loop
# displays 17 then bad luck from Italy for the 17th loop
# must use while, case

count="0"

while [ $count -le 20 ]
do
case $count in
	4) echo $count
		echo "bad luck from China"
	;;
	9) echo $count
		echo "bad luck from Japan"
	;;
	17) echo $count
		echo "bad luck from Italy"
	;;
	*)	
		echo $count
esac
(( count++ ))
done
