#!/usr/bin/env bash

# a script that displays content of the current directory
# in a list format
# where only the part of the name after the first dash is dispayed
# must use for loop (while and until are forbidden
# do not display hidden files

for i in *
do
	echo "$i" | cut -d'-' -f2
done
