#!/usr/bin/env bash
# gives you information about the school file use if else
# if file exists, school file exists else school not, print;
FILE="School"
if [ -e "$FILE" ]
then
	echo "school file exists"
	if [ ! -s "$FILE" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
