#!/usr/bin/env bash

# a script that gives you information about the school file
# must use if and else (case is forbidden)
# if file exists, school file exists else school file does not exist
# if exists, print; if the file is empty - school file is empty
# file not empty - school file is not empty
# regular file - school is a regular file
# not regular - nothing

FILE="School"

if [ -e "$FILE" ]
then
	echo "school file exists"
	if [ ! -s "$FILE" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
